version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mikrotik
      POSTGRES_USER: mikrotik
      POSTGRES_PASSWORD: mikrotik
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://mikrotik:mikrotik@db:5432/mikrotik
    depends_on:
      - db
volumes:
  db_data:
